#! /command/with-contenv bash

# Usage:
# Start: /package/admin/s6/command/s6-svc -o /run/service/consensus
# Stop:  /package/admin/s6/command/s6-svc -d /run/service/consensus

INITIAL_START=$(s6-svstat -o wantedup .)

# Do not restart
s6-svc -O .

# Kill children on exit
trap "kill 0" EXIT

if [ "${AUTO_START_CONSENSUS_SERVICE:-true}" == false ]; then
  # Exit on initial start
  if [ "${INITIAL_START}" == "true" ]; then
    exit
  fi
fi

exec /opt/hgcapp/services-hedera/HapiApp2.0/entrypoint.sh
