# SPDX-License-Identifier: Apache-2.0
name: "ZXC: Launch JRS Workflow"
on:
  workflow_call:
    inputs:
      workflow-file:
        description: "The file name of the workflow to be launched:"
        required: true
        type: string
      workflow-file-ref:
        description: "The branch, tag, or SHA containing the workflow file to be launched:"
        required: false
        type: string
      concurrency-group:
        description: "The concurrency group name to limit simultaneous workflows:"
        required: false
        type: string
      ref:
        description: "The branch, tag or SHA to checkout:"
        required: false
        type: string
      branch-name:
        description: "The branch name to use when generating a slack channel name automatically:"
        required: false
        type: string
    secrets:
      access-token:
        description: "The Github access token used to checkout the repository, submodules, and make GitHub API calls."
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  launch-workflow:
    name: Launch Workflow
    runs-on: hiero-network-node-linux-small-scheduler
    if: ${{ !github.event.workflow_call.repository.fork }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Install Github CLI
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}
        run: |
          curl -O -L -s https://github.com/cli/cli/releases/download/v2.5.0/gh_2.5.0_linux_amd64.deb
          sudo apt install -y ./gh_2.5.0_linux_amd64.deb
          rm -rf gh_2.5.0_linux_amd64.deb

      - name: Execute Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}
          WORKFLOW_FILE: ${{ inputs.workflow-file }}
          WORKFLOW_FILE_REF: ${{ inputs.workflow-file-ref || github.ref }}
          REPO: ${{ github.repository }}
          CONCURRENCY_GROUP: ${{ inputs.concurrency-group || '' }}
          REF: ${{ inputs.ref || '' }}
          BRANCH_NAME: ${{ inputs.branch-name || '' }}
        run: |
          ADDITIONAL_ARGS=()
          [[ -n "${CONCURRENCY_GROUP}" ]] && ADDITIONAL_ARGS+=("-f" "concurrency-group=${CONCURRENCY_GROUP}")
          [[ -n "${BRANCH_NAME}" ]] && ADDITIONAL_ARGS+=("-f" "branch-name=${BRANCH_NAME}")
          [[ -n "${REF}" ]] && ADDITIONAL_ARGS+=("-f" "ref=${REF}")
          gh workflow run ${WORKFLOW_FILE} -R "${REPO}" --ref "${WORKFLOW_FILE_REF}" "${ADDITIONAL_ARGS[@]}"
